def raise_exception():
    raise TypeError("A type exception has been raised.")

